# --------------------------------------------------------------------------
# JEKYLL SITE CONFIG FOR CHAOSS DEI PLAYBOOK
# --------------------------------------------------------------------------

title: "CHAOSS DEI Project Badging Outreach Playbook"
description: "Playbook for CHAOSS DEI Project Badging outreach ambassadors."
url: "https://adeyinkaoresanya.github.io"
baseurl: "/project-badging-outreach-playbook"

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Sidebar navigation
nav_items:
  - title: "CHAOSS DEI Project Badging Outreach Playbook"
    url: /
    children:
      -title: "Playbook Sections"
      url: /playbook-sections
      children:
        - title: "Objective & Audience"
          url: /playbook-sections/01-objective
        - title: "Outreach Ambassador Guidance"
          url: /playbook-sections/02-outreach-ambassador
        - title: "About Project Badging"
          url: /playbook-sections/03-about-project-badging
          

search_enabled: true
footer_content: "Maintained by the CHAOSS DEI Working Group"

