# title: "CHAOSS DEI Project Badging Playbook"
# description: "A guide for CHAOSS DEI Working Group members and outreach ambassadors."
# baseurl: "/wg-dei/project-badging-outreach-playbook" # hosting in subfolder
# url: "https://adeyinkaoresanya.github.io"

# # Use Just the Docs theme
# remote_theme: just-the-docs/just-the-docs

# # Enable search
# search_enabled: true

# # Footer (optional)
# footer_content: "Maintained by the CHAOSS DEI Working Group"

# # Optional: logo (if you want)
# # logo: "/assets/images/logo.png"





# --------------------------------------------------------------------------
# JEKYLL SITE CONFIG FOR CHAOSS DEI PLAYBOOK
# --------------------------------------------------------------------------

title: "CHAOSS DEI Project Badging Outreach Playbook"
description: "Playbook for CHAOSS DEI Project Badging outreach ambassadors."
url: "https://adeyinkaoresanya.github.io"
baseurl: "/wg-dei/project-badging-outreach-playbook"

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Sidebar navigation
nav_items:
  - title: "Playbook Sections"
    section: project-badging-outreach-playbook/playbook-sections

# # Top-right custom links
# aux_links:
#   "GitHub Repo":
#     - "https://github.com/adeyinkaoresanya/wg-dei"

# # Exclude files from build
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE.md
#   - README.md

# # Markdown settings
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

